### PR TITLE
Fix bytes decoding

### PR DESCRIPTION
**Pull request by alfredodeza**
Fixes http://tracker.ceph.com/issues/39489

And removes the bytes handling that is already done by remoto

### CODE REVIEW

**Comment by alfredodeza** [comment]
Should also fix issue http://tracker.ceph.com/issues/39489

**Comment by vasukulkarni** [comment]
Running tests on luminous and nautilus: 
1) Luminous: http://pulpito.ceph.com/vasu-2019-05-01_16:46:12-ceph-deploy-luminous-distro-basic-mira/
2) Nautilus: http://pulpito.ceph.com/vasu-2019-05-01_16:47:12-ceph-deploy-nautilus-distro-basic-mira/

@alfredodeza if you can rebase to master to pickup the boostrap fix that will be great, Also I believe with this fix will work for both python2 and python3?

**Comment by alfredodeza** [comment]
@vasukulkarni yes, these are for both py2 and py3

**Comment by vasukulkarni** [comment]
Only on Nautilus + Ubuntu

http://qa-proxy.ceph.com/teuthology/vasu-2019-05-01_16:47:12-ceph-deploy-nautilus-distro-basic-mira/3916496/teuthology.log

`
2019-05-02T22:41:50.415 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy.mon][INFO  ] Running gatherkeys...
2019-05-02T22:41:50.416 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy.gatherkeys][INFO  ] Storing keys in temp directory /tmp/tmpcdbo4uxv
2019-05-02T22:41:50.462 INFO:teuthology.orchestra.run.mira069.stderr:Warning: Permanently added 'mira101,172.21.8.118' (ECDSA) to the list of known hosts.
2019-05-02T22:41:50.834 INFO:teuthology.orchestra.run.mira069.stderr:[mira101][DEBUG ] connection detected need for sudo
2019-05-02T22:41:50.881 INFO:teuthology.orchestra.run.mira069.stderr:Warning: Permanently added 'mira101,172.21.8.118' (ECDSA) to the list of known hosts.
2019-05-02T22:41:51.263 INFO:teuthology.orchestra.run.mira069.stderr:[mira101][DEBUG ] connected to host: mira101
2019-05-02T22:41:51.313 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy.gatherkeys][INFO  ] Destroy temp directory /tmp/tmpcdbo4uxv
2019-05-02T22:41:51.315 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ] Traceback (most recent call last):
2019-05-02T22:41:51.316 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]   File "/home/ubuntu/cephtest/ceph-deploy/ceph_deploy/util/decorators.py", line 69, in newfunc
2019-05-02T22:41:51.318 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]     return f(*a, **kw)
2019-05-02T22:41:51.318 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]   File "/home/ubuntu/cephtest/ceph-deploy/ceph_deploy/cli.py", line 166, in _main
2019-05-02T22:41:51.319 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]     return args.func(args)
2019-05-02T22:41:51.319 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]   File "/home/ubuntu/cephtest/ceph-deploy/ceph_deploy/mon.py", line 470, in mon
2019-05-02T22:41:51.319 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]     mon_create_initial(args)
2019-05-02T22:41:51.319 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]   File "/home/ubuntu/cephtest/ceph-deploy/ceph_deploy/mon.py", line 454, in mon_create_initial
2019-05-02T22:41:51.319 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]     gatherkeys.gatherkeys(args)
2019-05-02T22:41:51.320 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]   File "/home/ubuntu/cephtest/ceph-deploy/ceph_deploy/gatherkeys.py", line 236, in gatherkeys
2019-05-02T22:41:51.320 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]     sucess = gatherkeys_with_mon(args, host, tmpd)
2019-05-02T22:41:51.320 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]   File "/home/ubuntu/cephtest/ceph-deploy/ceph_deploy/gatherkeys.py", line 165, in gatherkeys_with_mon
2019-05-02T22:41:51.321 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]     f.write(mon_key)
2019-05-02T22:41:51.321 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ] TypeError: write() argument must be str, not bytes
2019-05-02T22:41:51.322 INFO:teuthology.orchestra.run.mira069.stderr:[ceph_deploy][ERROR ]
2019-05-02T22:41:51.375 DEBUG:teuthology.orchestra.run:got remote process result: 1
`

**Comment by HacKanCuBa** [comment]
Ping @vasukulkarni

**Comment by vasukulkarni** [comment]
New traceback from ubuntu: http://pulpito.ceph.com/sage-2019-07-11_16:58:04-ceph-deploy-master-distro-basic-mira/

**Comment by alfredodeza** [comment]
@vasukulkarni the errors you are seeing don't look related to ceph-deploy or the changes in this PR.. Changes here address this:

```
2019-04-24T09:02:38.187 INFO:teuthology.orchestra.run.mira038.stderr:[ceph_deploy][ERROR ] TypeError: sequence item 0: expected a bytes-like object, str found
```

That doesn't appear in the logs you linked.

**Comment by alfredodeza** [comment]
If there are any follow up problems because of this PR I am happy to fix them!

**Comment by vasukulkarni** [comment]
@alfredodeza I think we might still see byte errors from the Ubuntu run, @yuriw can you schedule only the ubuntu runs please and update here? Thanks

**Comment by yuriw** [comment]
@vasukulkarni http://pulpito.ceph.com/teuthology-2019-07-12_18:51:39-ceph-deploy-master-distro-basic-mira/

**Comment by yuriw** [comment]
and this was scheduled by @liewegas http://pulpito.ceph.com/sage-2019-07-12_18:35:40-ceph-deploy-wip-sage-testing-2019-07-12-0901-distro-basic-mira/
@vasukulkarni FYI

**Comment by vasukulkarni** [comment]
@yuriw Thanks, Looks like its resolved!

**Pull request merged**
