### PR TITLE
Use ceph-volume for OSD operations

### PR DESCRIPTION
**Pull request by alfredodeza**
Major API changes for `osd` behavior:

* no longer allow to prepare+activate
* only support create
* drop `HOST:DISK` notation
* add `--data` and `--journal` flags
* only allow one deployment per call (one host, one osd)
* Will only work with Luminous onwards

**THIS IS A VERY BACKWARDS INCOMPATIBLE CHANGE**

Fixes: http://tracker.ceph.com/issues/22118

### CODE REVIEW

**Comment by alfredodeza** [comment]
@vasukulkarni this is good to be reviewed

**Comment by vasukulkarni** [comment]
@alfredodeza this looks really great, I am updating the qa task to use new syntax, once those tests are green, I will merge.

**Comment by alfredodeza** [comment]
@vasukulkarni thank you! that will certainly help. Once this is merged lets cut 2.0.0

**Comment by vasukulkarni** [comment]
Testing with https://github.com/ceph/ceph/pull/19244

**Comment by vasukulkarni** [comment]
@alfredodeza  I am seeing this error

http://qa-proxy.ceph.com/teuthology/vasu-2017-11-30_21:18:42-ceph-deploy-master-distro-basic-vps/1910179/teuthology.log
'''
2017-11-30T21:52:16.383 INFO:teuthology.orchestra.run.vpm121.stderr:[ceph_deploy.osd][DEBUG ] Creating OSD on cluster ceph with data device /dev/vg_hdd/lv_5
2017-11-30T21:52:16.448 INFO:teuthology.orchestra.run.vpm121.stderr:Warning: Permanently added 'vpm163,172.21.2.163' (ECDSA) to the list of known hosts.
2017-11-30T21:52:16.769 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][DEBUG ] connection detected need for sudo
2017-11-30T21:52:16.840 INFO:teuthology.orchestra.run.vpm121.stderr:Warning: Permanently added 'vpm163,172.21.2.163' (ECDSA) to the list of known hosts.
2017-11-30T21:52:17.162 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][DEBUG ] connected to host: vpm163
2017-11-30T21:52:17.162 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][DEBUG ] detect platform information from remote host
2017-11-30T21:52:17.192 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][DEBUG ] detect machine type
2017-11-30T21:52:17.201 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][DEBUG ] find the location of an executable
2017-11-30T21:52:17.203 INFO:teuthology.orchestra.run.vpm121.stderr:[ceph_deploy.osd][INFO  ] Distro info: CentOS Linux 7.4.1708 Core
2017-11-30T21:52:17.203 INFO:teuthology.orchestra.run.vpm121.stderr:[ceph_deploy.osd][DEBUG ] Deploying osd to vpm163
2017-11-30T21:52:17.203 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][DEBUG ] write cluster configuration to /etc/ceph/{cluster}.conf
2017-11-30T21:52:17.207 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][DEBUG ] find the location of an executable
2017-11-30T21:52:17.222 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][INFO  ] Running command: sudo /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/vg_hdd/lv_5
2017-11-30T21:52:22.821 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][WARNING] -->  TypeError: not all arguments converted during string formatting
2017-11-30T21:52:22.821 INFO:teuthology.orchestra.run.vpm121.stderr:[vpm163][ERROR ] RuntimeError: command returned non-zero exit status: 1
2017-11-30T21:52:22.821 INFO:teuthology.orchestra.run.vpm121.stderr:[ceph_deploy.osd][ERROR ] Failed to execute command: /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/vg_hdd/lv_5
2017-11-30T21:52:22.822 INFO:teuthology.orchestra.run.vpm121.stderr:[ceph_deploy][ERROR ] GenericError: Failed to create 1 OSDs
2017-11-30T21:52:22.822 INFO:teuthology.orchestra.run.vpm121.stderr:
2017-11-30T21:52:22.854 INFO:tasks.ceph_deploy:Error encountered, logging exception before tearing down ceph-deploy
2017-11-30T21:52:22.855 INFO:tasks.ceph_deploy:Traceback (most recent call last):
'''

**Comment by alfredodeza** [comment]
I thought this was improved in the error reporting side of things. But what is happening here is that the syntax for a logical volume is vg/lv not /dev/vg/lv

Can you try vg/lv and open an issue on the tracker to point out that the error reporting here is basically terrible?

**Comment by alfredodeza** [comment]
@vasukulkarni I can't reproduce this. And I don't know where the exception is happening. So a couple of things here that are useful:

* ceph-volume writes all exceptions to a log file in /var/log/ceph/ceph-volume.log - we might want to capture that
* `CEPH_VOLUME_DEBUG=1` will make exceptions be out on the terminal, it is a good idea to set that in when calling out to ceph-volume to capture stuff in the foreground

**Comment by alfredodeza** [comment]
Reproduced, tracker ticket created at http://tracker.ceph.com/issues/22299

**Comment by vasukulkarni** [comment]
@alfredodeza thanks, fixing the final pv/lv format for create, should get results today.

**Comment by vasukulkarni** [comment]
Bluestore test worked fine: http://pulpito.ceph.com/vasu-2017-12-01_19:10:33-ceph-deploy-master-distro-basic-vps/1912252/
Filestore also worked but failed for different reason: http://qa-proxy.ceph.com/teuthology/vasu-2017-12-01_19:10:33-ceph-deploy-master-distro-basic-vps/1912254/teuthology.log

**Comment by vasukulkarni** [comment]
@alfredodeza  I just have a minor test isue with filestore, I will try to fix that so that both PRs can go in at the same time.

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2017-12-01_22:21:24-ceph-deploy-master-distro-basic-vps/

**Pull request merged**
