### PR TITLE
Support deploy on deepin and Uos

### PR DESCRIPTION
**Pull request by movie0125**
Support deployment of ceph on deepin and uos operating systems

### CODE REVIEW

**Comment by movie0125** [comment]
https://tracker.ceph.com/issues/49201

**Comment by movie0125** [comment]
my test environment is deepin and Uos server V20 

$ ceph-deploy new movie
[ceph_deploy.conf][DEBUG ] found configuration file at: /home/uos/.cephdeploy.conf
[ceph_deploy.cli][INFO  ] Invoked (2.1.0): /usr/bin/ceph-deploy new movie
[ceph_deploy.cli][INFO  ] ceph-deploy options:
[ceph_deploy.cli][INFO  ]  username                      : None
[ceph_deploy.cli][INFO  ]  verbose                       : False
[ceph_deploy.cli][INFO  ]  overwrite_conf                : False
[ceph_deploy.cli][INFO  ]  quiet                         : False
[ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf object at 0x7f10518488d0>
[ceph_deploy.cli][INFO  ]  cluster                       : ceph
[ceph_deploy.cli][INFO  ]  ssh_copykey                   : True
[ceph_deploy.cli][INFO  ]  mon                           : ['movie']
[ceph_deploy.cli][INFO  ]  func                          : <function new at 0x7f105181f1b8>
[ceph_deploy.cli][INFO  ]  public_network                : None
[ceph_deploy.cli][INFO  ]  ceph_conf                     : None
[ceph_deploy.cli][INFO  ]  cluster_network               : None
[ceph_deploy.cli][INFO  ]  default_release               : False
[ceph_deploy.cli][INFO  ]  fsid                          : None
[ceph_deploy.new][DEBUG ] Creating new cluster named ceph
[ceph_deploy.new][INFO  ] making sure passwordless SSH succeeds
[movie][DEBUG ] connection detected need for sudo
[movie][DEBUG ] connected to host: movie 
[movie][DEBUG ] detect platform information from remote host
[movie][DEBUG ] detect machine type
[movie][DEBUG ] find the location of an executable
[movie][INFO  ] Running command: sudo /bin/ip link show
[movie][INFO  ] Running command: sudo /bin/ip addr show
[movie][DEBUG ] IP addresses found: [u'10.20.7.193']
[ceph_deploy.new][DEBUG ] Resolving host movie
[ceph_deploy.new][DEBUG ] Monitor movie at 10.20.7.193
[ceph_deploy.new][DEBUG ] Monitor initial members are ['movie']
[ceph_deploy.new][DEBUG ] Monitor addrs are ['10.20.7.193']
[ceph_deploy.new][DEBUG ] Creating a random mon key...
[ceph_deploy.new][DEBUG ] Writing monitor keyring to ceph.mon.keyring...
[ceph_deploy.new][DEBUG ] Writing initial config to ceph.conf...

**Comment by movie0125** [comment]
@tchaikov  
hello  please help check this patch

**Comment by tchaikov** [comment]
ok to test.

**Comment by tchaikov** [comment]
@movie0125 please note, we don't maintain ceph-deploy anymore.

**Pull request closed without merging**
