### PR TITLE
[RM-17053] cleanup: using load_raw to replace old practice

### PR DESCRIPTION
**Pull request by minshenglin**
Signed-off-by: MinSheng Lin <minsheng.l@inwinstack.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
OK to test

**Comment by alfredodeza** [comment]
@minshenglin could you elaborate a bit more on the *why* ? The calls you are changing used `parse` which in turn trims indentation and does some normalization on variables.

Is there a bug?

**Comment by minshenglin** [comment]
@alfredodeza I replace those practice because I think `load_raw` is more suitable for reading config file without parsing.

Actually, this modify just like PR #158 to do.

**Comment by vasukulkarni** [comment]
@alfredodeza This seems to have broken the osd create

`
RuntimeError: config file /etc/ceph/ceph.conf exists with different content; use --overwrite-conf to overwrite
2016-08-19T22:20:23.950 INFO:teuthology.orchestra.run.vpm033.stderr:[ceph_deploy][ERROR ] GenericError: Failed to create 1 OSDs
2016-08-19T22:20:23.950 INFO:teuthology.orchestra.run.vpm033.stderr:
2016-08-19T22:20:23.950 INFO:tasks.ceph_deploy:Error encountered, logging exception before tearing down ceph-deploy
2016-08-19T22:20:23.951 INFO:tasks.ceph_deploy:Traceback (most recent call last):
  File "/home/teuthworker/src/ceph-qa-suite_jewel/tasks/ceph_deploy.py", line 301, in build_ceph_cluster
    raise RuntimeError("ceph-deploy: Failed to create osds")
RuntimeError: ceph-deploy: Failed to create osds
`

**Comment by vasukulkarni** [comment]
http://qa-proxy.ceph.com/teuthology/vasu-2016-08-19_22:07:27-ceph-deploy-jewel---basic-vps/375342/teuthology.log

**Pull request merged**
