### PR TITLE
shaman/chacra support

### PR DESCRIPTION
**Pull request by alfredodeza**
Will make `--dev` and `--dev-commit` talk to shaman which redirects to actual repo contents from chacra instances

See http://tracker.ceph.com/issues/18169

### CODE REVIEW

**Comment by andrewschoen** [comment]
Tests failed because ``ERROR:   py34: InterpreterNotFound: python3.4``. Do we need to tell tox to ignore missing interpreters in these tests?

**Comment by andrewschoen** [comment]
Otherwise, this looks good to me. 👍

**Comment by alfredodeza** [comment]
I am not concerned on the py3.4 failure (I did get them tested locally)

**Comment by vasukulkarni** [comment]
thanks @alfredodeza for adding this :+1:

**Pull request merged**
