### PR TITLE
Refactor ceph executable

### PR DESCRIPTION
**Pull request by mazebuhu**
Minimal refactor of 'ceph-disk' and 'ceph' commands to get them from system.executable_path

Signed-off-by: Martin Palma <martin@palma.bz>

### CODE REVIEW

**Comment by alfredodeza** [comment]
please test this

**Comment by alfredodeza** [comment]
ok to test

**Comment by mazebuhu** [comment]
Not sure why Jenkins is failing? Local tests all succeeded + deployed a test cluster with my version.

**Comment by alfredodeza** [comment]
@mazebuhu we had a couple of issues with the build system that we just fixed. For a while in ceph-deploy we have been trying to certain conventions in commit messages, would you mind rebasing and changing your commits to comply with the new conventions?

The contributing file will point you in the right direction: https://github.com/ceph/ceph-deploy/blob/master/CONTRIBUTING.rst

And I already created the issue in the tracker for you, so you would just need to use the ticket ID: http://tracker.ceph.com/issues/13847

**Comment by smithfarm** [comment]
@mazebuhu The merge commits don't look good in a pull request. Also, it looks like you have three commits from @alfredodeza in there. 8059332 is a duplicate of https://github.com/ceph/ceph-deploy/commit/17a477ec0dd453e7da661fb86e0047feb33a3539 for example.

**Comment by smithfarm** [comment]
@mazebuhu 814ac23 and a31589b are the same commit?

**Comment by mazebuhu** [comment]
@smithfarm yes, you a right. I might messed things up when rebasing. I will close this PR and submit a new one.

**Pull request closed without merging**
