### PR TITLE
[RM-19266] add the opportunity to specify block.db and block.wal

### PR DESCRIPTION
**Pull request by Andrey1994**
add the opportunity to specify block.db and block.wal in bluestore

### CODE REVIEW

**Comment by alfredodeza** [comment]
OK to test

**Comment by Andrey1994** [comment]
py26: commands succeeded
  py27: commands succeeded
ERROR:   py34: InterpreterNotFound: python3.4

**Comment by alfredodeza** [comment]
This looks OK to me, but I am unsure about the functionality needed in ceph-disk to make this correct for bluestore

/cc @vasukulkarni @liewegas @dachary 

Can any of you guys take a look and approve/merge if it looks OK?

**Comment by vasukulkarni** [comment]
I haven't looked at bluestore with ceph-deploy yet, I think we should eventually add some tests to master branch with these options but for now if we can see how this cli works with logs should be OK to merge or others in CC can take care,  @Andrey1994 would you also please paste the cli run from your branch, Thanks.

**Comment by Andrey1994** [comment]
"would you also please paste the cli run from your branch"
ceph-deploy osd create **--bluestore --block-wal /dev/nvme0n1 --block-db /dev/nvme0n1** p30:sdb
And it works exactly as I need:
**ls /var/lib/ceph/osd/ceph-1/ -l**
lrwxrwxrwx 1 ceph ceph  58 Mar 13 13:01 block.db -> /dev/disk/by-partuuid/**f281f282-8104-41c7-a957-0afcba8f9366**
lrwxrwxrwx 1 ceph ceph  58 Mar 13 13:01 block.wal -> /dev/disk/by-partuuid/**16d5e010-3335-40dc-8e4d-19b564757fce**
..........
blkid /dev/**nvme0n1p1**
/dev/nvme0n1p1: PARTLABEL="ceph block.db" PARTUUID="**f281f282-8104-41c7-a957-0afcba8f9366**"
blkid /dev/**nvme0n1p2**
/dev/nvme0n1p2: PARTLABEL="ceph block.wal" PARTUUID="1**6d5e010-3335-40dc-8e4d-19b564757fce**"

And I agreed with liewegas about --block.db and --block-db

**Comment by liewegas** [comment]
Do you mind submitting a PR for ceph-disk so that --block-db and --block-wal work (as well as --block.db and --block.wal)?

**Comment by Andrey1994** [comment]
It will be necessary to fix it for all arguments listed here:

-   --block.db-uuid UUID  unique uuid to assign to the block.db
-   --block.db-file       verify that BLOCK.DB is a file
-   --block.db-dev        verify that BLOCK.DB is a block device
-   --block.db BLOCKDB    path to the device or file for bluestore block.db
-   --block.wal-uuid UUID unique uuid to assign to the block.wal
-   --block.wal-file      verify that BLOCK.WAL is a file
-   --block.wal-dev       verify that BLOCK.WAL is a block device
-   --block.wal BLOCKWAL  path to the device or file for bluestore block.wal

and maybe we add them to ceph-deploy(I am unsure that all of them needed in ceph-deploy, for my current work just block.wal and block.db was required)

**Pull request merged**
