### PR TITLE
support for distro Mint which is based on ubuntu

### PR DESCRIPTION
**Pull request by honkiko**
Signed-off-by: Hong Zhiguo <zhiguohong@tencent.com>

### CODE REVIEW

**Comment by honkiko** [comment]
Works on my "Linux Mint 17 Qiana". Should also works on other recent versions.

**Comment by alfredodeza** [comment]
ok to test

**Comment by alfredodeza** [comment]
@honkiko I don't see any issues with this change, but Mint is not one of the officially supported distributions. Having it here in ceph-deploy would imply that we are supporting it.

**Comment by ktdreyer** [comment]
Personally I don't see the harm in taking this - "supported" is a fuzzy word :)

**Comment by liewegas** [comment]
Yeah, I think we should make ceph-deploy work with as many target distros as is practical.

**Pull request merged**
