### PR TITLE
Fix: keyring permissions where world readable

### PR DESCRIPTION
**Pull request by osynge**
Reported in https://bugzilla.suse.com/show_bug.cgi?id=920926
by  Andreas Stieger <astieger@suse.com>

Before thsi fix to umask for keyring handling, After execution
of ceph-deploy, all keyrings have mode 644.

The documented ceph-deploy procedure by creating a dedicated
admin user, and keys will be readable to all other (non-admin)
users as well, thus leaking authentication credentials.

The fix uses umask to resolve the writing of keyfiles.

Signed-off-by: Owen Synge <osynge@suse.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
OK to test

**Comment by alfredodeza** [comment]
ok to test

**Comment by trhoden** [comment]
@osynge This looks good to me. Thanks for the fix!

Some changes recently went in that make this need to be rebased off of master.  Can you do that?  Then I'll merge it it.

**Comment by osynge** [comment]
@trhoden I think this is rebased now? If anythign is wrong please let me know.

**Comment by trhoden** [comment]
@osynge Looks like you did a merge instead of a rebase? I wouldn't expect to see a merge commit (there are now two commits in this PR).

Assuming that you had set up github.com/ceph/ceph-deploy.git as your `upstream` repo, you would normally do something like the following:

```
git fetch upstream
git checkout wip_key_perms
git rebase upstream master
git push -f origin wip_key_perms
```

Did you do something along these lines?

I'm happy to chat about this on #ceph-devel too if you like.

**Comment by osynge** [comment]
What I did was 
git checkout wip_key_perms
git diff master > patch
git co master
git fetch upstream
git push
git branch wip_key_perms_rebase
git checkout wip_key_perms_rebase
patch -p1 < patch
git commit .
git push --set-upstream origin wip_key_perms
--
Your way would have been less work :)

**Comment by trhoden** [comment]
I'm closing this for https://github.com/ceph/ceph-deploy/pull/272

I manually pulled in @osynge branch and rebased, but had to do some funny work to resolve conflicts.  More than I wanted to document here in the comments.  So instead I just created a new PR for it.

**Pull request closed without merging**
