### PR TITLE
[RM-13528] apt: no gpg key is installed allows unauthenticated packages

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
> this is a global setting and very unsafe to set it for an install and no set it back. Wouldn't the flag --allow-unauthenticated be better as a one time use case?

That would be a flag to **ceph-deploy install** ?

**Comment by alfredodeza** [comment]
`apt-get` allows a `--allow-unauthenticated` flag to do an install of a package without checking the authenticity. This would be a better option I think than setting a system wide change that would be permanent.

See: https://help.ubuntu.com/community/SecureApt in "Validation of Release files and Packages" section.

**Comment by dachary** [comment]
@alfredodeza something like https://github.com/ceph/ceph-deploy/pull/362/files#diff-129ed243ea17f372404615bf22419ed1R58 is what you advise (except it would be **--allow-unauthenticated** intsead of **--force-yes** ) ?

**Comment by alfredodeza** [comment]
Something like that yes, where 'extra flags' would mean to use the `--allow-unauthenticated`

**Pull request closed without merging**
