### PR TITLE
[RM-17567] Start mon by systemd/sysvint/upstart after adding mon

### PR DESCRIPTION
**Pull request by adshao**

### CODE REVIEW

**Comment by vasukulkarni** [comment]
All the repetitive code for various OS'es is not required, the deleting part in common is fine and probably calling a function that does start in generic way for all OS'es should be good way to avoid repetition.

**Comment by adshao** [comment]
hi @vasukulkarni , so we need to remove the mon folder (including create.py) from all OS'es?

**Comment by alfredodeza** [comment]
This looks OK to me. @vasukulkarni can you double check please?

**Comment by alfredodeza** [comment]
OK to test

**Comment by vasukulkarni** [comment]
@alfredodeza the new changes does look good to me  :+1:  , I believe jenkins failure is due to py34

**Pull request merged**
