### PR TITLE
Tests altlinux platform for pull request #472

### PR DESCRIPTION
**Pull request by mrandybu**
Was added tests ALT Linux platform for pull request #472, enough it's tests?

### CODE REVIEW

**Comment by mrandybu** [comment]
@alfredodeza Tests needed?

**Comment by alfredodeza** [comment]
ok to test

**Comment by alfredodeza** [comment]
Seems like there are some valid tests failures. Mind addressing those? For example:

    E   ImportError: No module named 'ceph_deploy.hosts.altlinux'

**Comment by mrandybu** [comment]
@alfredodeza fixed

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by mrandybu** [comment]
@alfredodeza build errors are not related to tests

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
Seems I need to fix this one:

    E                   ImportError: import error in ceph_deploy.util.system.remoto.process: No module named 'ceph_deploy.util.system.remoto'; 'ceph_deploy.util.system' is not a package

Being tracked by: http://tracker.ceph.com/issues/37848

**Comment by alfredodeza** [comment]
This will need a rebase after https://github.com/ceph/ceph-deploy/pull/481 gets merged.

**Comment by mrandybu** [comment]
@alfredodeza ok? :)

**Comment by alfredodeza** [comment]
jenkins test this please

**Pull request merged**
