### PR TITLE
osd commands support "/dev/disk/by-path/".

### PR DESCRIPTION
**Pull request by osynge**
osd arguments can contain disk definitions by path.

/dev/disk/by-path/pci-0000:00:1f.2-ata-1.0

But these require : to delimit the host, disk and potentially journal.
Since argparse swallows \"' characters. But since \" and \' evaluate
to " and ' respectively we can use shlex to handle this correctly.

Hence a valid ceph-deploy command can now be:

```
ceph-deploy osd prepare --zap \
    ceph-node3:\'/dev/disk/by-path/pci-0000:00:1f.2-ata-1.0\'
```

or:

```
ceph-deploy osd prepare --zap \
    ceph-node3:\"/dev/disk/by-path/pci-0000:00:1f.2-ata-1.0\"
```

Signed-off-by: Owen Synge osynge@suse.com

### CODE REVIEW

**Comment by osynge** [comment]
Am I correct in believing that the tests are failing for no good reason?

They seem to fail for me on both master and with this patch.

**Comment by alfredodeza** [comment]
@osynge I would say they are failing correctly with assertion Errors. I would also suggest that this patch needs unit tests for the new logic/behavior added

**Comment by alfredodeza** [comment]
Everything passes for me in master:

    $ tox
    ...
      py26: commands succeeded
      py27: commands succeeded
      flake8: commands succeeded
      congratulations :)
    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.

**Comment by osynge** [comment]
Running tox I get the output:

2029 passed, 16 skipped in 46.46 seconds 

But I do get some errors that I am not able to find python 2.6

**Comment by alfredodeza** [comment]
@osynge you need to have Python 2.6 and 2.7 installed to be able to run all the environments that ceph-deploy is configured to execute with tox. Again: this PR has valid failures that you need to correct, and I would strongly suggest adding unit tests to support your changes.

**Comment by osynge** [comment]
@alfredodeza I did have a bug, annoying issues with touple and list that had no impact, but made the test suite fail.

I followed your advice and added some tests to support the current behaviour and the changes.

Unrelated to this patch : would you recommend adding the same / similar tests for "ceph disk create" and "ceph disk activate" or is adding them for "ceph disk prepare" enough?

**Pull request closed without merging**
